### ISSUE TITLE
Please update tor.exe to latest version.

### ISSUE THREAD

**Issue by quasin** [HelloZeroNet/ZeroNet-win#1]
Please update tor.exe to latest version. Or add "ExitRelay 0" to torrc-defaults. For improve security reasone.
Thanks.

**Comment by HelloZeroNet** [comment]
Based on the [docs ](https://2019.www.torproject.org/docs/tor-manual.html.en) the ExitRelay option does nothing if you are not running the tor client as a Tor relay/server
